apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - helmrelease.yaml
  - helmrelease-tailscale.yaml
  - ingress.yaml
  - ingress-homepage-tailscale.yaml
  - certificate.yaml
