apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - configmap.yaml
  - pvc.yaml
  - helmrelease.yaml
  - service.yaml
  - ingress.yaml
  - certificate.yaml
  - networkpolicy.yaml
  - sealedsecret-plex-claim.yaml
