---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - configmap.yaml
  - postgresql.yaml
  - helmrelease.yaml
  - networkpolicy.yaml
  - networkpolicy-postgresql.yaml
  - sealedsecret-rreading-glasses-credentials.yaml
