apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sure-finance
resources:
  - namespace.yaml
  - helmrelease.yaml
  - ingress.yaml
  - certificate.yaml
  - networkpolicy.yaml
  - sealedsecret-sure-credentials.yaml
  - postgresql.yaml
  - redis.yaml
