apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
