apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.dnsPort }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.service.dnsPort }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
