apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pdb-traefik.yaml
  - pdb-longhorn.yaml
  - pdb-metallb.yaml
  - pdb-prometheus.yaml
  - pdb-loki.yaml
  - pdb-cert-manager.yaml
  - pdb-sealed-secrets.yaml
  - pdb-kyverno.yaml
  - pdb-flux.yaml
