apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository-kyverno.yaml
  - helmrelease-kyverno.yaml
  - cluster-policies
  - kyverno
  - network-policies
  - rwx-access
