apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-web-tailscale
  namespace: media
  annotations:
    tailscale.com/proxy-group: homelab-ingress
spec:
  ingressClassName: tailscale
  rules:
    - host: calibre
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calibre-web
                port:
                  number: 8083
  tls:
    - hosts:
        - calibre
