apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless
  namespace: paperless
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`paperless.homelab`)
      kind: Rule
      services:
        - name: paperless
          port: 8000
  tls:
    secretName: paperless-tls
