apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - require-resources-limits.yaml
  - block-risky-capabilities.yaml
  - enforce-namespace-labels.yaml
  - mutate-topology-spread.yaml
  - mutate-ingress-annotations.yaml
  - disallow-latest-tag.yaml
  - require-image-signatures.yaml
