apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cooklang-tailscale
  namespace: media
  annotations:
    tailscale.com/tags: "tag:k8s-operator"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: cooklang
      port:
        number: 9080
  tls:
    - hosts:
        - cooklang
