---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phantom
  namespace: siloarr
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: phantom.homelab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whisparr
                port:
                  number: 6969
  tls:
    - hosts:
        - phantom.homelab
      secretName: phantom-tls
