apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - pvc.yaml
  - helmrelease.yaml
  - certificate.yaml
  - ingress.yaml
  - ingress-phantom-tailscale.yaml
