apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepository-longhorn.yaml
  - helmrelease-longhorn.yaml
  - ingress-longhorn.yaml
  - storageclass-longhorn-retain.yaml
