---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - configmap.yaml
  - pvc.yaml
  - helmrelease.yaml
  - ingress.yaml
  - ingress-prowlarr-tailscale.yaml
  - certificate.yaml
