apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - loki/helmrepository-loki.yaml
  - loki/helmrelease-loki.yaml
  - loki/promtail/helmrepository-promtail.yaml
  - loki/promtail/helmrelease-promtail.yaml
