apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kaneo-web
  namespace: kaneo
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: kaneo.homelab
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kaneo-api
                port:
                  number: 1337
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kaneo-web
                port:
                  number: 80
  tls:
    - hosts:
        - kaneo.homelab
      secretName: kaneo-tls
