apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kaneo
resources:
  - namespace.yaml
  - helmrelease.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - sealedsecret-kaneo-credentials.yaml
