apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository-prometheus-community.yaml
  - helmrepository-grafana.yaml
  - helmrepository-kubernetes-event-exporter.yaml
  - helmrepository-kured.yaml
  - helmrepository-node-problem-detector.yaml
  - helmrelease-kube-prometheus-stack.yaml
  - helmrelease-kubernetes-event-exporter.yaml
  - helmrelease-kured.yaml
  - helmrelease-node-problem-detector.yaml
  - sealedsecret-grafana-admin-creds.yaml
  - prometheusrules-alerts.yaml
  - prometheusrules-node-health-alerts.yaml
  - ingress-grafana.yaml
  - servicemonitor-node-feature-discovery.yaml
  - servicemonitor-intel-gpu-plugin.yaml
  - servicemonitor-kured.yaml
  - servicemonitor-node-problem-detector.yaml
  - custom-dashboards/
  - dashboards/
