apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository-prometheus-community.yaml
  - helmrepository-grafana.yaml
  - helmrepository-kured.yaml
  - helmrepository-node-problem-detector.yaml
  - helmrelease-kube-prometheus-stack.yaml
  - helmrelease-kured.yaml
  - helmrelease-node-problem-detector.yaml
  - sealedsecret-grafana-admin-creds.yaml
  - prometheusrules-alerts.yaml
  - prometheusrules-node-health-alerts.yaml
  - ingress-grafana.yaml
  - ingress-grafana-tailscale.yaml
  - servicemonitor-node-feature-discovery.yaml
  - servicemonitor-intel-gpu-plugin.yaml
  - servicemonitor-kured.yaml
  - servicemonitor-node-problem-detector.yaml
  - probe-plex.yaml
  - probe-overseerr.yaml
  - probe-sonarr.yaml
  - probe-radarr.yaml
  - probe-bazarr.yaml
  - probe-prowlarr.yaml
  - probe-sabnzbd.yaml
  - probe-paperless.yaml
  - probe-calibre.yaml
  - probe-bookshelf.yaml
  - probe-kaneo.yaml
  - probe-homebox.yaml
  - probe-sure-finance.yaml
  - probe-grafana.yaml
  - probe-longhorn.yaml
  - custom-dashboards/
  - dashboards/
