apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kaneo-git-repo.yaml
  - plex-helm-repo.yaml
  - bjw-s-helm-repo.yaml
  - vicsufer-helm-repo.yaml
  - zekker6-helm-repo.yaml
