apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - disallow-host-namespaces.yaml
  - restrict-host-ports.yaml
  - restrict-capabilities.yaml
  - disallow-privilege-escalation.yaml
  - require-run-as-nonroot.yaml
  - restrict-seccomp.yaml
  - restrict-apparmor.yaml
