apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homebox
resources:
  - namespace.yaml
  - helmrelease.yaml
  - ingress.yaml
  - ingress-homebox-tailscale.yaml
  - certificate.yaml
  - networkpolicy.yaml
