apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds
  - namespaces
  - networking
  - storage
  - node-bootstrap/iscsi
  - node-bootstrap/gpu
  - node-bootstrap/media-mount-handler
  - monitoring
  - logging
  - cert-manager
  - sealed-secrets
  - accelerators/intel-gpu
  - policies
  - scheduling
  - tailscale
