apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kaneo
  - plex
  - prowlarr
  - sonarr
  - radarr
  - sabnzbd
  - bazarr
  - overseerr
  - sure-finance
  - paperless-ngx
  - homebox
  - bookshelf
  - rreading-glasses
  - calibre-web
  - kindle-sender
  - homepage
  - syncthing
