apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-widgets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  widgets.yaml: |
    {{- toYaml .Values.config.widgets | nindent 4 }}
