apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-services
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  services.yaml: |
    {{- toYaml .Values.config.services | nindent 4 }}
