apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny.yaml
  - allow-dns.yaml
  - allow-ingress-controller.yaml
  - allow-monitoring.yaml
  - allow-monitoring-ingress.yaml
  - allow-prometheus-internal.yaml
  - allow-sealed-secrets.yaml
  - allow-flux-system.yaml
