apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-tailscale
  namespace: paperless
  annotations:
    tailscale.com/proxy-group: homelab-ingress
spec:
  ingressClassName: tailscale
  rules:
    - host: paperless
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless-paperless-ngx
                port:
                  number: 8000
  tls:
    - hosts:
        - paperless
