apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless
resources:
  - namespace.yaml
  - helmrelease.yaml
  - ingress.yaml
  - certificate.yaml
  - networkpolicy.yaml
  - sealedsecret-paperless-credentials.yaml
